name: Build courses

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'courses/**'

jobs:
  build_courses:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v7
      - name: Build courses
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: courses
          root_file: |
            kokkos_cpu.tex
            kokkos_gpu.tex
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
