name: Test exercises

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_test_exercises:
    strategy:
      matrix:
        arch:
          - name: x86_64
            os: ubuntu-24.04
          - name: aarch64
            os: ubuntu-24.04-arm
        backend:
          - name: openmp
            image: kokkos_cpu_interactive
            flags: -DKokkos_ENABLE_OPENMP=ON
          - name: cuda
            image: kokkos_gpu_interactive
            flags: -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_AMPERE80=ON
    runs-on: ${{ matrix.arch.os }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - run: |
          docker pull gitlab-registry.in2p3.fr/cta-lapp/cours/gray_scott_revolutions/grayscottbasecontainer/${{ matrix.backend.image }}:1.1.3
          docker buildx imagetools inspect gitlab-registry.in2p3.fr/cta-lapp/cours/gray_scott_revolutions/grayscottbasecontainer/${{ matrix.backend.image }}:1.1.3
          docker create --name inspectme gitlab-registry.in2p3.fr/cta-lapp/cours/gray_scott_revolutions/grayscottbasecontainer/${{ matrix.backend.image }}:1.1.3
          docker export inspectme -o rootfs.tar
          mkdir rootfs
          tar -xf rootfs.tar -C rootfs
          file rootfs/usr/bin/uname
          file rootfs/bin/sh
